[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "neurosym-agent"
version = "0.1.0"
description = "Neurosymbolic Agent Protocol implementation"
authors = [{name="RFI-IRFOS"}]
dependencies = ["pydantic"]
