[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pmp-agent"
version = "0.1.0"
description = "Executable BEF + PML agent"
authors = [{name = "RFI-IRFOS"}]
requires-python = ">=3.9"
